DROP TABLE IF EXISTS MINION;
DROP TABLE IF EXISTS VERSIONED_MINION;

CREATE TABLE MINION
(
    ID   INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    primary key (ID)
);

CREATE TABLE VERSIONED_MINION
(
    ID      INT PRIMARY KEY,
    NAME    VARCHAR(255),
    VERSION INT
);